//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTHoaDon()
        {
            this.GioHangs = new HashSet<GioHang>();
        }
    
        public int MaCTHD { get; set; }
        public string MaHD { get; set; }
        public Nullable<int> MaHang { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual Hang Hang { get; set; }
        public virtual HoaDon HoaDon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHangs { get; set; }
    }
}
