//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int MaCTHD { get; set; }
        public Nullable<int> MaHang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public int MaUser { get; set; }
        public int MaGioHang { get; set; }
    
        public virtual CTHoaDon CTHoaDon { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
