//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hang()
        {
            this.CTHoaDons = new HashSet<CTHoaDon>();
        }
    
        public int MaHang { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<int> MaThuongHieu { get; set; }
        public string TenHang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<long> DonGia { get; set; }
        public string HinhAnh { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHoaDon> CTHoaDons { get; set; }
        public virtual Loai Loai { get; set; }
        public virtual ThuongHieu ThuongHieu { get; set; }
    }
}
