//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.GioHangs = new HashSet<GioHang>();
        }
    
        public int MaUser { get; set; }
        public string Username { get; set; }
        public string Pass { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string SDT { get; set; }
        public string ProvinceID { get; set; }
        public string DistrictID { get; set; }
        public string WardID { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> MaQuyen { get; set; }
    
        public virtual District District { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHangs { get; set; }
        public virtual Province Province { get; set; }
        public virtual Quyen Quyen { get; set; }
        public virtual Ward Ward { get; set; }
    }
}
